import re

text="Hello Rishwanth, Welcome to 1 the pytho34tn Concept of Regular Expression"
res=re.findall('\AHello',text)
print("\A: ",res)
print("-"*79)
res=re.findall(r'\bExpress',text)
print("\\b: ",res)
print("-"*79)
res=re.findall(r'ssion\b',text)
print("after,\\b: ",res)
print("-"*79)
res=re.findall('\Bcome',text)
print("\B: ",res)
print("-"*79)
res=re.findall(r'\d',text)
print("\(d): ",res)
print("-"*79)
res=re.findall('\D',text)
print("\D: ",res)
print("-"*79)
res=re.findall(r'\s',text)
print("\(s): ",res)
print("-"*79)
res=re.findall('\S',text)
print("\S: ",res)
print("-"*79)
res=re.findall(r'\w',text)
print("\(w): ",res)
print("-"*79)
res=re.findall('\W',text)
print("\W: ",res)
print("-"*79)
res=re.findall('Expression\Z',text)
print("\Z: ",res)
print("-"*79)
