import re
text="Hello RIshwanth, Welcome to the python Concept of Regular \ Expression."
res=re.search('Concept',text)
print(res)
print("--"*30)
print(res.group())
print("--"*30)
print(res.start())
print("--"*30)
print(res.end())
print("--"*30)
print(res.span())
print("--"*30)
print(res.re)
print("--"*30)
print(res.string)
print("--"*30)
res=re.search(r"\\",text)
print(res)